urls = [
    # 'https://vt.tiktok.com/ZSjuajPdt/',
    # 'https://vt.tiktok.com/ZSjuakn3S/',
    # 'https://vt.tiktok.com/ZSjuaLytt/',
    # 'https://vt.tiktok.com/ZSjua82Qm/',
    # 'https://vt.tiktok.com/ZSjuaB27E/',
    # 'https://vt.tiktok.com/ZSjuahv99/',
    # 'https://vt.tiktok.com/ZSjuaShyJ/',
    # 'https://vt.tiktok.com/ZSjuahaTh/',
    # 'https://vt.tiktok.com/ZSjuahRnv/',
    # 'https://vt.tiktok.com/ZSjuaRtG4/',
    # 'https://vt.tiktok.com/ZSjuaRB8k/',
    # 'https://vt.tiktok.com/ZSjua2Bqb/',
    # 'https://vt.tiktok.com/ZSjuaR7wC/',
    # 'https://vt.tiktok.com/ZSjuaLY6U/',
    # 'https://vt.tiktok.com/ZSjuaDM7C/',
    # 'https://vt.tiktok.com/ZSjuaNXVW/',
    # 'https://vt.tiktok.com/ZSjuaAMPG/',
    # 'https://vt.tiktok.com/ZSjuaLpeK/',
    # 'https://vt.tiktok.com/ZSjuaAg5Y/',
    # 'https://vt.tiktok.com/ZSjuaYryA/',
    # 'https://vt.tiktok.com/ZSju5CYqT/',
    # 'https://vt.tiktok.com/ZSjuaeJah/',
    # 'https://vt.tiktok.com/ZSju5qSep/',
    # 'https://vt.tiktok.com/ZSju5VX7t/',
    # 'https://vt.tiktok.com/ZSju5nxnR/',
    # 'https://vt.tiktok.com/ZSjuaJHMm/',
    # 'https://vt.tiktok.com/ZSju5pMdJ/',
    # 'https://vt.tiktok.com/ZSju5vSCJ/',
    # 'https://vt.tiktok.com/ZSju5pMH4/',
    # 'https://vt.tiktok.com/ZSju54fYF/',
    # 'https://vt.tiktok.com/ZSju5Cheh/',
    # 'https://vt.tiktok.com/ZSju53MTB/',
    # 'https://vt.tiktok.com/ZSju5Xus2/',
    # 'https://vt.tiktok.com/ZSju5okPH/',
    # 'https://vt.tiktok.com/ZSju5sAjc/',
    # 'https://vt.tiktok.com/ZSju5CNgP/',
    # 'https://vt.tiktok.com/ZSju57vd3/',
    # 'https://vt.tiktok.com/ZSju5tptq/',
    # 'https://vt.tiktok.com/ZSju5TthU/',
    # 'https://vt.tiktok.com/ZSjuaFRo3/',
    # 'https://vt.tiktok.com/ZSju5yJkX/',
    'https://vt.tiktok.com/ZSju5r9pq/',
    'https://vt.tiktok.com/ZSju54kFY/',
    'https://vt.tiktok.com/ZSju5jxFB/',
    'https://vt.tiktok.com/ZSju5Y4Mo/',
    'https://vt.tiktok.com/ZSju5Y4Mo/',
    'https://vt.tiktok.com/ZSju55bMd/',
    'https://vt.tiktok.com/ZSju5B2Jt/',
    'https://vt.tiktok.com/ZSju5Y5GJ/',
    'https://vt.tiktok.com/ZSju5M1pn/',
    'https://vt.tiktok.com/ZSju5M1pn/',
    'https://vt.tiktok.com/ZSju5foQ1/',
    'https://vt.tiktok.com/ZSju5MFH5/',
    'https://vt.tiktok.com/ZSju56Tog/',
    'https://vt.tiktok.com/ZSju5tw33/',
    'https://vt.tiktok.com/ZSju5qgBg/',
    'https://vt.tiktok.com/ZSju5ggfx/',
    'https://vt.tiktok.com/ZSju5cNF3/',
    'https://vt.tiktok.com/ZSju5K9U4/',
    'https://vt.tiktok.com/ZSju5qeCK/'
]